# Standards: 1.2
---
- name: Create required directories
  loop: "{{ checkmk_default_folders + checkmk_extra_folders }}"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    recurse: True
    state: directory
  tags:
    - checkmk

- name: Write default config
  notify:
    - Restart checkmk
  template:
    src: default.j2
    dest: /etc/default/checkmk
  tags:
    - checkmk

- name: Write service file
  notify:
    - Restart checkmk
  template:
    src: service.j2
    dest: /etc/systemd/system/checkmk.service
  tags:
    - checkmk

- name: Start checkmk service
  systemd:
    name: checkmk
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - checkmk

...
