---
- name: Create required directories
  loop: "{{ checkmk_default_folders + checkmk_extra_folders }}"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - checkmk

- name: Write default config
  notify:
    - Restart checkmk
  template:
    src: default.j2
    dest: /etc/default/checkmk
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - checkmk

- name: Write service file
  notify:
    - Restart checkmk
  template:
    src: service.j2
    dest: /etc/systemd/system/checkmk.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - checkmk

- name: Pull docker image
  when: checkmk_pull_image
  docker_image:
    name: "{{ checkmk_image }}"
    source: pull
  tags:
    - checkmk

- name: Start checkmk service
  systemd:
    name: checkmk
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - checkmk

...
